// Generated by CoffeeScript 1.7.1
(function() {
  var Cas1ValidationReader, Cas2ValidationReader, Casable, http, https, url, xmls2js,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  url = require('url');

  xmls2js = require('xml2js');

  http = require('http');

  https = require('https');

  Cas2ValidationReader = (function() {
    Cas2ValidationReader.prototype.validationUrl = function() {
      return '/serviceValidate';
    };

    function Cas2ValidationReader() {}

    Cas2ValidationReader.prototype.read = function(body, callback) {
      return xmls2js.parseString(body, function(error, result) {
        var auth, session;
        if ('cas:authenticationFailure' in result['cas:serviceResponse']) {
          return callback(null, "Invalid Ticket or Service");
        } else if ('cas:authenticationSuccess' in result['cas:serviceResponse']) {
          auth = result['cas:serviceResponse']['cas:authenticationSuccess'][0];
          session = {
            id: auth['cas:user'][0],
            name: auth['cas:name'][0],
            surname: auth['cas:surname'][0],
            email: auth['cas:email'][0],
            salt: auth['cas:salt'][0],
            passwordHash: auth['cas:passwordHash'][0]
          };
          return callback(session);
        }
      });
    };

    return Cas2ValidationReader;

  })();

  Cas1ValidationReader = (function() {
    Cas1ValidationReader.prototype.validationUrl = function() {
      return '/validate';
    };

    function Cas1ValidationReader() {}

    Cas1ValidationReader.prototype.read = function(body, callback) {
      var lines;
      lines = body.split('\n');
      if (lines.length >= 1) {
        if (lines[0] === 'no') {
          return callback(null, "Invalid Ticket or Service");
        }
      } else if (lines[0] === 'yes' && lines.length >= 2) {
        return callback({
          id: lines[1]
        });
      }
    };

    return Cas1ValidationReader;

  })();

  Casable = (function() {
    function Casable(ssoBaseURL, config) {
      this.ssoBaseURL = ssoBaseURL;
      this.config = config != null ? config : {};
      this.validate = __bind(this.validate, this);
      this.authenticate = __bind(this.authenticate, this);
      this.logout = __bind(this.logout, this);
      this.login = __bind(this.login, this);
      this.buildServiceUrl = __bind(this.buildServiceUrl, this);
      this.parsedBaseUrl = url.parse(this.ssoBaseURL);
      this.logoutDestination = this.config.logoutPath || '/';
      this.casVersion = this.config.casVersion || '2.0';
      this.loginURL = this.ssoBaseURL + '/login';
      this.logoutURL = this.ssoBaseURL + '/logout';
      this.cookieName = this.config.cookieName;
    }

    Casable.prototype.buildServiceUrl = function(req) {
      return url.format({
        host: req.headers.host,
        protocol: req.protocol,
        pathname: req.route.path
      });
    };

    Casable.prototype.buildLogoutUrl = function(req) {
      return url.format({
        host: req.headers.host,
        protocol: req.protocol,
        pathname: this.logoutURL
      });
    };

    Casable.prototype.login = function(res, req) {
      var redirectURL;
      redirectURL = url.parse(this.loginURL, true);
      redirectURL.query.service = this.buildServiceUrl(req);
      return res.redirect(url.format(redirectURL));
    };

    Casable.prototype.logout = function(req, res) {
      var redirectURL;
      if (req.session != null) {
        req.session.authenticatedUser = null;
      }
      req.authenticatedUser = null;
      redirectURL = url.parse(this.logoutURL);
      return res.redirect(url.format(redirectURL));
    };

    Casable.prototype.authenticate = function(req, res, next) {
      var ticket;
      if (req.route.path === '/logout') {
        this.logout(req, res);
        next();
        return;
      }
      if (this.cookieName) {
        if (!req.cookies[this.cookieName]) {
          if (req.session != null) {
            req.session.authenticatedUser = null;
          }
          req.authenticatedUser = null;
          this.login(res, req);
          return;
        }
      }
      if ((req.session != null) && (req.session.authenticatedUser != null)) {
        req.authenticatedUser = req.session.authenticatedUser;
        next();
        return;
      }
      ticket = req.param('ticket');
      if (ticket != null) {
        return this.validate(req, ticket, (function(_this) {
          return function(user, error) {
            if ((req.session != null) && (user != null)) {
              req.session.authenticatedUser = user;
            }
            req.authenticatedUser = user;
            next();
          };
        })(this));
      } else {
        return this.login(res, req);
      }
    };

    Casable.prototype.validate = function(req, ticket, callback) {
      var httpGet, reader, validateRequest, validateUrl;
      reader = this.casVersion === "2.0" ? new Cas2ValidationReader() : new Cas1ValidationReader();
      delete req.query.ticket;
      validateUrl = url.format({
        pathname: "" + (reader.validationUrl()),
        query: {
          ticket: ticket,
          service: this.buildServiceUrl(req)
        }
      });
      httpGet = function(res) {
        var body;
        res.setEncoding('utf8');
        body = '';
        res.on('data', function(chunk) {
          return body += chunk;
        });
        return res.on('end', function() {
          return reader.read(body, callback);
        });
      };
      if (this.parsedBaseUrl.protocol === 'https:') {
        validateRequest = https.get("" + this.parsedBaseUrl.href + validateUrl, httpGet);
      } else {
        validateRequest = http.get("" + this.parsedBaseUrl.href + validateUrl, httpGet);
      }
      return validateRequest.on('error', function(error) {
        return callback(null, error);
      });
    };

    return Casable;

  })();

  exports.authentication = function(ssoBaseURL, config) {
    if (config == null) {
      config = {};
    }
    return new Casable(ssoBaseURL, config).authenticate;
  };

}).call(this);
